export const queryKeys = {
    sessions: ['sessions'] as const,
    session: (sessionId: string) => ['session', sessionId] as const,
    messages: (sessionId: string) => ['messages', sessionId] as const,
    machines: ['machines'] as const,
    gitStatus: (sessionId: string, cwd?: string) => ['git-status', sessionId, cwd ?? ''] as const,
    sessionFiles: (sessionId: string, query: string, cwd?: string) => ['session-files', sessionId, query, cwd ?? ''] as const,
    sessionDirectory: (sessionId: string, path: string, cwd?: string) => ['session-directory', sessionId, path, cwd ?? ''] as const,
    sessionFile: (sessionId: string, path: string, cwd?: string) => ['session-file', sessionId, path, cwd ?? ''] as const,
    gitFileDiff: (sessionId: string, path: string, staged?: boolean, cwd?: string) => [
        'git-file-diff',
        sessionId,
        path,
        staged ? 'staged' : 'unstaged',
        cwd ?? ''
    ] as const,
    slashCommands: (sessionId: string) => ['slash-commands', sessionId] as const,
    skills: (sessionId: string) => ['skills', sessionId] as const,
    sessionUiState: (sessionId: string) => ['session-ui-state', sessionId] as const,
    credentials: ['credentials'] as const,
    machineCredentials: (machineId: string) => ['machine-credentials', machineId] as const,
    apiKeys: ['api-keys'] as const,
    apiKeyTokens: (apiKeyId: string) => ['api-key-tokens', apiKeyId] as const,
    managedMachines: ['managed-machines'] as const,
    preferences: ['preferences'] as const,
    speakers: ['speakers'] as const,
}
